<?php 
/** @var \UIComponents\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \UIComponents\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'admin/applicationsedit',
		array(
			'action'		=> 'edit',
			'application_id'		=> $this->applications_id,
		)
	));
	$form->setAttribute('class', 'form-xhr');
	$form->prepare();
		
	$formHTML = $this->form()->openTag($form);
	$formHTML .= $oComponents->formGroup($form, "name");
	$formHTML .= $oComponents->formGroup($form, "shortname");
	$formHTML .= '<hr />'; 
	$formHTML .= $oComponents->formGroup($form, "path");
	$formHTML .= $oComponents->formGroup($form, "url");
	$formHTML .= '<hr />'; 
	$formHTML .= $oComponents->formGroup($form, "client_id");
	$formHTML .= $oComponents->formGroup($form, "email");
	$formHTML .= '<hr />'; 
	$formHTML .= $this->formHidden($form->get('application_id'));
	$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'button primary btn btn-primary')));
	$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'button secondary btn btn-default')));
	$formHTML .= '<a class="button alert btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'. $this->url('admin/applicationsedit') .'">'. $this->translate("cancel") .'</a>';
	$formHTML .=  $this->form()->closeTag($form);
		
	echo $formHTML;
}
