<div class="table-responsive">
	<table id="applicationstable" class="table table-striped table-hover datatable crud" data-src="<?php echo $this->url('admin/applicationsedit') ?>">
		<thead>
			<tr>
				<th data-column="name" data-search="name,extraname"><?php echo $this->translate("name")?></th>
				<th data-column="url"><?php echo $this->translate("url")?></th>
				<th data-column="clientname"><?php echo $this->translate("client")?></th>
				<th class="actions">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($applicationsdata as $application) : ?>
			<tr>
				<td><?php echo $this->escapeHtml($application->name).(!empty($application->shortname) ? ', '.$this->escapeHtml($application->shortname) : '' ); ?></td>
				<td><?php echo $this->escapeHtml($application->url); ?></td>
				<td><?php echo $this->escapeHtml($application->clientname); ?></td>
				<td>
					<div class="btn-group btn-group-xs">
						<a class="btn btn-default btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/applicationsedit',
							array('action'=>'edit', 'application_id' => $application->applications_id));?>"><span class="fa fa-pencil"></span> <?php echo $this->translate("edit"); ?></a>
						<a class="btn btn-default btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/applicationsedit',
							array('action'=>'delete', 'application_id' => $application->applications_id));?>"><span class="fa fa-trash-o"></span> <?php echo $this->translate("delete"); ?></a>
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<?php echo $this->output ?>
