<?php 
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

$messages = $this->flashMessenger()->renderCurrent('error', array('error alert alert-error'));
$messages .= $this->flashMessenger()->renderCurrent('warning', array('warning alert alert-warning'));
$messages .= $this->flashMessenger()->renderCurrent('success', array('success alert alert-success'));
$messages .= $this->flashMessenger()->renderCurrent('info', array('info alert alert-info'));
	
if (!$showForm) {
	//echo $messages . $content;
	
	if ($isXHR) {
		$html = $oComponents->Modal()
			->setHeader( $this->translate("add user") )
			->setContent(
				array(
					'tagname' => 'div',
					'classname' => 'modal-body alert-wrap',
					'content' => $messages,
				)
			);
	} else {
		$html = $oComponents->Panel()
			->setHeader( $this->translate("add user") )
			->setContent(
				array(
					'tagname' => 'div',
					'classname' => 'panel-body alert-wrap',
					'content' => $messages,
				)
			);
	}
	echo $html;
	
} else { 

	$form->setAttribute('action', $this->url('admin/default', array('controller' => 'users', 'action' => 'add')));
	$form->setAttribute('class', 'form-xhr');
	$form->prepare();
		
	$formHTML = $this->form()->openTag($form);
	$formHTML .= $oComponents->formGroup($form, "username");
	$formHTML .= $oComponents->formGroup($form, "email");
	$formHTML .= $oComponents->formGroup($form, "display_name");
	$formHTML .= '<hr />';
	$formHTML .= $oComponents->formGroup($form, "aclrole");
	$formHTML .= $oComponents->formGroup($form, "state");
	$formHTML .= '<hr />';
	$formHTML .= $oComponents->formGroup($form, "password");
	$formHTML .= '<hr />'; 
	$formHTML .= $this->formHidden($form->get('user_id'));
	$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary')));
	$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default')));
	$formHTML .= '<a class="btn btn-danger btn-cta-xhr-close" href="'. $this->url('admin/default') .'">'. $this->translate("cancel") .'</a>';
	$formHTML .=  $this->form()->closeTag($form);
		
		
	if ($isXHR) {
		$html = $oComponents->Modal()
			->setHeader( $this->translate("add user") )
			->setContent(
				$messages . $formHTML
			);
	} else {
		$html = $oComponents->Panel()
			->setHeader( $this->translate("add user") )
			->setContent(
				$formHTML
			);
	}
	echo $html;
}

