<?php 
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

$messages = $this->flashMessenger()->render('error', array('error alert alert-error _flashmessages'));
$messages .= $this->flashMessenger()->render('warning', array('warning alert alert-warning _flashmessages'));
$messages .= $this->flashMessenger()->render('success', array('success alert alert-success _flashmessages'));
$messages .= $this->flashMessenger()->render('info', array('info alert alert-info _flashmessages'));
	
if (!$showForm) {
	//echo $messages . $content;
	
	if ($isXHR) {
		$html = $oComponents->Modal()
			->setHeader( $this->translate("add user") )
			->setContent(
				array(
					'tagname' => 'div',
					'classname' => 'alert-wrap',
					'content' => $messages,
				)
			);
	} else {
		$html = $oComponents->Panel()
			->setHeader( $this->translate("add user") )
			->setContent(
				$messages
			);
	}
	echo $html;
	
} else { 

	$form->setAttribute('action', $this->url('admin/default', array('controller' => 'users', 'action' => 'add')));
	$form->setAttribute('class', 'form-xhr');
	$form->prepare();
		
	$formHTML = $this->form()->openTag($form);
	/*$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('username'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('username'));
	$formHTML .= $this->formInput($form->get('username')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('username'));
	$formHTML .= '</div>';*/
	$formHTML .= $this->formgroup(array("form" => $form, "field" => "username"));
	
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('email'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('email'));
	$formHTML .= $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('email'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('display_name'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('display_name'));
	$formHTML .= $this->formInput($form->get('display_name')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('display_name'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('password'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('password'));
	$formHTML .= $this->formInput($form->get('password')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('password'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('street'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('street'));
	$formHTML .= $this->formInput($form->get('street')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('street'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('city'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('city'));
	$formHTML .= $this->formInput($form->get('city')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('city'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('phone'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('phone'));
	$formHTML .= $this->formInput($form->get('phone')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('phone'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('aclrole'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('aclrole'));
	$formHTML .= $this->formSelect($form->get('aclrole')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('aclrole'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('state'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('state'));
	$formHTML .= $this->formSelect($form->get('state')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('state'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= $this->formHidden($form->get('user_id'));
	$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary')));
	$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default')));
	$formHTML .= '<a class="btn btn-danger btn-cta-xhr-close" href="'. $this->url('admin/default') .'">'. $this->translate("cancel") .'</a>';
	$formHTML .=  $this->form()->closeTag($form);
		
		
	if ($isXHR) {
		$html = $oComponents->Modal()
			->setHeader( $this->translate("add user") )
			->setContent(
				$messages . $formHTML
			);
	} else {
		$html = $oComponents->Panel()
			->setHeader( $this->translate("add user") )
			->setContent(
				$formHTML
			);
	}
	echo $html;
}

