<?php 
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if (!$showForm) {
	echo $content;
} else { 

	$form->setAttribute('action', $this->url('admin/default', array('controller' => 'users', 'action' => 'add')));
	$form->setAttribute('class', 'form-xhr');
	$form->prepare();
		
	$formHTML = ''; // $this->form()->openTag($form);
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('username'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('username'));
	$formHTML .= $this->formInput($form->get('username')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('username'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('email'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('email'));
	$formHTML .= $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('email'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('display_name'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('display_name'));
	$formHTML .= $this->formInput($form->get('display_name')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('display_name'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('password'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('password'));
	$formHTML .= $this->formInput($form->get('password')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('password'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('street'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('street'));
	$formHTML .= $this->formInput($form->get('street')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('street'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('city'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('city'));
	$formHTML .= $this->formInput($form->get('city')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('city'));
	$formHTML .= '</div>';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('phone'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('phone'));
	$formHTML .= $this->formInput($form->get('phone')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('phone'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('aclrole'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('aclrole'));
	$formHTML .= $this->formSelect($form->get('aclrole')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('aclrole'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= '<div class="form-group'.(!empty($this->formElementErrors($form->get('state'))) ? ' has-error' : '') .'">';
	$formHTML .= $this->formLabel($form->get('state'));
	$formHTML .= $this->formSelect($form->get('state')->setAttributes(array('class' => 'form-control')));
	$formHTML .= $this->formElementErrors($form->get('state'));
	$formHTML .= '</div>';
	$formHTML .= '<hr />';
	$formHTML .= $this->formHidden($form->get('user_id'));
	$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary')));
	$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default')));
	$formHTML .= '<a class="btn btn-danger btn-cta-xhr-close" href="'. $this->url('admin/default') .'">'. $this->translate("cancel") .'</a>';
	//$formHTML .=  $this->form()->closeTag($form);
		
		
	if ($isXHR) {
		$html = $this->form()->openTag($form) . $oComponents->Modal()
			->setHeader( $this->translate("add user") )
			->setContent(
				$formHTML
			)
			. $this->form()->closeTag($form)
		;
	} else {
		$html = $this->form()->openTag($form) . $oComponents->Panel()
			->setHeader( $this->translate("add user") )
			->setContent(
				$formHTML
			)
			->setFooter()
			. $this->form()->closeTag($form)
		;
	}
	echo $html;
 /* ?>
<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><?php echo $this->translate("add user");</span>
	</div>
	<div class="panel-body">
		<?php 
			$form->setAttribute('action', $this->url('admin/default', array('controller' => 'users', 'action' => 'add')));
			$form->setAttribute('class', 'form-xhr');
			$form->prepare();
			
			echo $this->form()->openTag($form);
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('username')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('username'));
				<?php echo $this->formInput($form->get('username')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('username'));
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('email')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('email'));
				<?php echo $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('email'));
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('display_name')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('display_name'));
				<?php echo $this->formInput($form->get('display_name')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('display_name'));
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('password')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('password'));
				<?php echo $this->formInput($form->get('password')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('password'));
			</div>
			<hr />
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('street')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('street'));
				<?php echo $this->formInput($form->get('street')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('street'));
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('city')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('city'));
				<?php echo $this->formInput($form->get('city')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('city'));
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('phone')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('phone'));
				<?php echo $this->formInput($form->get('phone')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('phone'));
			</div>
			<hr />
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('aclrole')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('aclrole'));
				<?php echo $this->formSelect($form->get('aclrole')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('aclrole'));
			</div>
			<hr />
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('state')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('state'));
				<?php echo $this->formSelect($form->get('state')->setAttributes(array('class' => 'form-control')));
				<?php echo $this->formElementErrors($form->get('state'));
			</div>
			<hr />
			<?php echo $this->formHidden($form->get('user_id'));
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary')));
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default')));
			<a class="btn btn-danger btn-cta-xhr-close" href="<?php echo $this->url('admin/default');"><?php echo $this->translate("cancel");</a>
		<?php echo $this->form()->closeTag($form);
	</div>
</div>
<?php */ 
} 
?>
