<?php if (!$showForm) {
	echo $content;
} else { ?>
<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><?php echo $this->translate("delete user"); ?></span>
	</div>
	<div class="panel-body">
		<p><?php echo $this->translate("Do you really want to delete this user?"); ?></p>
		<p>
			'<?php echo $this->escapeHtml($user->username); ?>' - 
			'<?php echo $this->escapeHtml($user->display_name); ?>' - 
			'<?php echo $this->escapeHtml($user->email); ?>'?
		</p>
		<?php
		$url = $this->url('admin/default', array(
		    'controller' => 'users',
		    'action'     => 'delete',
		    'user_id'    => $user->user_id,
		));
		?>
		<form action="<?php echo $url; ?>" method="post" class="form-xhr">
			<div>
				<input type="hidden" name="id" value="<?php echo (int) $user->user_id; ?>" />
				<input class="btn btn-primary" type="submit" name="del" value="<?php echo $this->translate("delete"); ?>" />
				<a class="btn btn-danger btn-cta-xhr-close" href="<?php echo $this->url('admin/default'); ?>"><?php echo $this->translate("cancel"); ?></a>
			</div>
		</form>
	</div>
</div>
<?php } ?>