<?php
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {	
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'admin/default',
		array(
			'controller'	=> 'users',
			'action'		=> 'edit',
			'user_id'		=> $this->user_id,
		)
	));
	$form->setAttribute('class', 'form-xhr');
	$form->prepare();
		
	$formHTML = $this->form()->openTag($form);
	$formHTML .= $oComponents->formGroup($form, "username");
	$formHTML .= $oComponents->formGroup($form, "email");
	$formHTML .= $oComponents->formGroup($form, "display_name");
	$formHTML .= '<hr />';
	$formHTML .= $oComponents->formGroup($form, "aclrole");
	$formHTML .= $oComponents->formGroup($form, "state");
	$formHTML .= '<hr />';
	$formHTML .= $oComponents->formGroup($form, "password");
	$formHTML .= '<hr />'; 
	$formHTML .= $this->formHidden($form->get('user_id'));
	$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'button primary btn btn-primary')));
	$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'button btn btn-default')));
	$formHTML .= '<a class="button alert btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'. $this->url('admin/default', array("controller" => "users")) .'">'. $this->translate("cancel") .'</a>';
	$formHTML .=  $this->form()->closeTag($form);
			
	echo $formHTML;
}