<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><?php echo $this->translate("manage users"); ?></span>
	</div>
	<div class="panel-body panel-toolbar">
		<div class="btn-group btn-group-sm">
			<a class="btn btn-default btn-clean btn-sm btn-cta-xhr" data-actioncontext="usertable" href="<?php echo $this->url('admin/default', array('controller'=>'users', 'action'=>'add'));?>"><span class="fa fa-plus"></span> <?php echo $this->translate("add user")?></a>
		</div>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table id="usertable" class="table table-striped table-hover datatable" data-src="<?php echo $this->url('admin/default', array('controller'=>'users', 'action'=>'index'));?>">
				<thead>
					<tr>
					    <th data-column="username"><?php echo $this->translate("user name")?></th>
					    <th data-column="email"><?php echo $this->translate("email")?></th>
					    <th data-column="aclrole"><?php echo $this->translate("role")?></th>
					    <th class="actions">&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($userdata as $user) : ?>
					<tr>
					    <td><?php echo $this->escapeHtml($user->username);?></td>
					    <td><?php echo $this->escapeHtml($user->email);?></td>
					    <td><?php echo $this->escapeHtml($user->aclrole);?></td>
					    <td>
						    <div class="btn-group btn-group-xs">
						        <a class="btn btn-default btn-xs btn-clean btn-cta-xhr" href="<?php echo $this->url('admin/default',
						            array('controller'=>'users', 'action'=>'edit', 'user_id' => $user->user_id));?>"><span class="fa fa-pencil"></span> <?php echo $this->translate("edit"); ?></a>
						        <a class="btn btn-default btn-xs btn-clean btn-cta-xhr" href="<?php echo $this->url('admin/default',
						            array('controller'=>'users', 'action'=>'delete', 'user_id' => $user->user_id));?>"><span class="fa fa-trash-o"></span> <?php echo $this->translate("delete"); ?></a>
						    </div>
					    </td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<?php echo $this->output ?>
	</div>
</div>
