<div class="well well-sm">
	<ul class="nav nav-pills">
    	<li role="presentation"><a href="<?php echo $this->url('admin/default', array('controller'=>'users', 'action'=>'add'));?>"><?php echo $this->translate("add user")?></a></li>
	</ul>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><?php echo $this->translate("manage users"); ?></span>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<tr>
				    <th><?php echo $this->translate("user name")?></th>
				    <th><?php echo $this->translate("email")?></th>
				    <th><?php echo $this->translate("role")?></th>
				    <th>&nbsp;</th>
				</tr>
				<?php foreach ($userdata as $user) : ?>
				<tr>
				    <td><?php echo $this->escapeHtml($user->username);?></td>
				    <td><?php echo $this->escapeHtml($user->email);?></td>
				    <td><?php echo $this->escapeHtml($user->aclrole);?></td>
				    <td>
				        <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/default',
				            array('controller'=>'users', 'action'=>'edit', 'user_id' => $user->user_id));?>"><?php echo $this->translate("edit"); ?></a>
				        <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/default',
				            array('controller'=>'users', 'action'=>'delete', 'user_id' => $user->user_id));?>"><?php echo $this->translate("delete"); ?></a>
				    </td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
		<?php echo $this->output ?>
	</div>
</div>
