<h1>Hallo [myApplication] Admin!</h1>
<p>Bitte best&auml;tige die [myApplication] Aktivierung f&uuml;r: <?php echo $this->escapehtml($display_name); ?>, <?php echo $this->escapehtml($email); ?></p>
<p><a href="<?php echo $this->escapehtml($activation_url); ?>" target="_blank"><?php echo $this->escapehtml($activation_url); ?></a></p>
<br />
<br />
<p>
Beste Gr&uuml;&szlig;e<br />
<br />
Dein [myApplication] Team
</p>