<h1>Hallo <?php echo $this->escapehtml($display_name) ?>!</h1>
<p>Bitte folge dem Link, um ein neues Passwort festzulegen:</p>
<p><a href="<?php echo $this->escapehtml($resetpassword_url); ?>" target="_blank"><?php echo $this->escapehtml($resetpassword_url); ?></a></p>
<br />
<p>Du kannst Dich auch mit deinem bisherigen Passwort normal anmelden:</p>
<p><a href="<?php echo $this->escapehtml($login_url); ?>" target="_blank"><?php echo $this->escapehtml($login_url); ?></a></p>
<br />
<br />
<p>
Beste Gr&uuml;&szlig;e<br />
<br />
Dein [myApplication] Team
</p>