<?php
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {
	$url = $this->url('admin/clientsedit', array(
		'action'	 => 'delete',
		'client_id'	 => $clients->clients_id,
	));
	$formHTML = array(
		'<p>'.$this->translate("Do you really want to delete this client?").'</p>',
		'<p>'.
			'&quot;'.$this->escapeHtml($clients->name).'&quot;, '.
				'&quot;'.$this->escapeHtml($clients->extraname).'&quot;'.
		'</p>',
		'<form action="'.$url.'" method="post" class="form-xhr">'.
			'<div>'.
				'<input type="hidden" name="id" value="'.((int) $clients->clients_id).'" />'.
				'<input class="button primary btn btn-primary" type="submit" name="del" value="'.$this->translate("delete").'" />'.
				'<a class="button alert btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'.$this->url('admin/clientsedit').'">'.$this->translate("cancel").'</a>'.
			'</div>'.
		'</form>'
	);
	echo implode("", $formHTML);
} 
