<div class="table-responsive">
	<table id="clientstable" class="table table-striped table-hover datatable crud" data-src="<?php echo $this->url('admin/clientsedit') ?>">
		<thead>
			<tr>
				<th data-column="name" data-search="name,extraname"><?php echo $this->translate("name")?></th>
				<th data-column="email"><?php echo $this->translate("email")?></th>
				<th data-column="contact"><?php echo $this->translate("contact")?></th>
				<th class="actions">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($clientsdata as $clients) : ?>
			<tr>
				<td><?php echo $this->escapeHtml($clients->name).(!empty($clients->extraname) ? ', '.$this->escapeHtml($clients->extraname) : '' ); ?></td>
				<td><?php echo $this->escapeHtml($clients->email); ?></td>
				<td><?php echo $this->escapeHtml($clients->contact); ?></td>
				<td>
					<div class="btn-group btn-group-xs">
						<a class="btn btn-default btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/clientsedit',
							array('action'=>'edit', 'client_id' => $clients->clients_id));?>"><span class="fa fa-pencil"></span> <?php echo $this->translate("edit"); ?></a>
						<a class="btn btn-default btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/clientsedit',
							array('action'=>'delete', 'client_id' => $clients->clients_id));?>"><span class="fa fa-trash-o"></span> <?php echo $this->translate("delete"); ?></a>
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<?php echo $this->output ?>
