<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Neue Rolle hinzufügen"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php
			$form->setAttribute('action', $this->url('admin/acledit', array('action' => 'addrole')));
			$form->prepare();
			echo $this->form()->openTag($form); ?>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('roleslug')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('roleslug')); ?>
				<?php echo $this->formInput($form->get('roleslug')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('roleslug')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('rolename')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('rolename')); ?>
				<?php echo $this->formInput($form->get('rolename')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('rolename')); ?>
			</div>
			<hr />
			<?php echo $this->formHidden($form->get('aclroles_id')); ?>
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<a class="btn btn-danger" href="<?php echo $this->url('admin/acledit'); ?>"><?php echo $this->translate("abbrechen"); ?></a>
		<?php echo $this->form()->closeTag($form); ?>
	</div>
</div>
