<?php 
/** @var \UIComponents\View\Helper\Utilities $oUtilities **/
$oUtilities = $this->Utilities();
/** @var \UIComponents\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'admin/acledit',
        array(
            'action'        => 'editresource',
            'acl_id'        => $acl_id,
        )
    ));
    $form->setAttribute('class', 'form-xhr');
    $form->prepare();
        
    $formHTML = $this->form()->openTag($form);
    $form->get('resourceslug')->setAttribute('disabled', false);
    $formHTML .= $oComponents->formGroup($form, "resourceslug");
    $formHTML .= $oComponents->formGroup($form, "resourcename");
    $formHTML .= '<hr />'; 
    $formHTML .= $this->formHidden($form->get('aclresources_id'));
    $formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'button primary btn btn-primary')));
    $formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'button secondary btn btn-default')));
    $formHTML .= '<a class="button alert btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'. $this->url('admin/acledit') .'">'. $this->translate("cancel") .'</a>';
    $formHTML .=  $this->form()->closeTag($form);
        
    echo $formHTML;
}