<?php 
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'admin/acledit',
		array(
			'action'		=> 'editacl',
			'acl_id'		=> $acl_id,
		)
	));
	$form->setAttribute('class', 'form-xhr');
	$oRoles = $form->get('aclroles_id');
	$valueoptions = array();
	foreach ($roles as $role) {
		$valueoptions[$role->aclroles_id] = $role->rolename;
	}
	$oRoles->setAttribute('disabled', false);
	$oRoles->setValueOptions($valueoptions);
	$oResources = $form->get('aclresources_id');
	$valueoptions = array();
	foreach ($resources as $resource) {
		$valueoptions[$resource->aclresources_id] = $resource->resourcename;
	}
	$oResources->setAttribute('disabled', false);
	$oResources->setValueOptions($valueoptions);
	$form->prepare();
		
	$formHTML = $this->form()->openTag($form);
	$form->get('aclroles_id')->setAttribute('disabled', false);
	$form->get('aclresources_id')->setAttribute('disabled', false);
	$formHTML .= $oComponents->formGroup($form, "aclroles_id");
	$formHTML .= $oComponents->formGroup($form, "aclresources_id");
	$formHTML .= '<hr />'; 
	$formHTML .= $oComponents->formGroup($form, "state");
	$formHTML .= '<hr />'; 
	$formHTML .= $this->formHidden($form->get('acl_id'));
	$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary')));
	$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default')));
	$formHTML .= '<a class="btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'. $this->url('admin/acledit') .'">'. $this->translate("cancel") .'</a>';
	$formHTML .=  $this->form()->closeTag($form);
		
	echo $formHTML;
}