<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><?php echo $this->translate("manage permissions"); ?></span>
	</div>
	<div class="panel-body panel-toolbar">
		<div class="btn-group btn-group-sm">
			<a class="btn btn-default btn-clean btn-cta-xhr cta-xhr-modal btn-sm" href="<?php echo $this->url('admin/acledit', array('action'=>'addrole'));?>"><span class="fa fa-plus"></span> <?php echo $this->translate("add role")?></a>
			<a class="btn btn-default btn-clean btn-sm" href="<?php echo $this->url('admin/acledit', array('action'=>'roles'));?>"><span class="fa fa-users"></span> <?php echo $this->translate("manage roles")?></a>
			<a class="btn btn-default btn-clean btn-cta-xhr cta-xhr-modal btn-sm" href="<?php echo $this->url('admin/acledit', array('action'=>'addresource'));?>"><span class="fa fa-plus"></span> <?php echo $this->translate("add resource")?></a>
			<a class="btn btn-default btn-clean btn-sm" href="<?php echo $this->url('admin/acledit', array('action'=>'resources'));?>"><span class="fa fa-list-alt"></span> <?php echo $this->translate("manage resources")?></a>
		</div>
	</div>
	<div class="panel-body">
	
		<?php include 'index.matrix.phtml'; ?>
		
		<?php echo $this->output ?>
	</div>
</div>
