<div class="well well-sm">
	<ul class="nav nav-pills">
		<li role="presentation"><a href="<?php echo $this->url('admin/acledit', array('action'=>'addrole'));?>"><?php echo $this->translate("Rolle hinzufügen")?></a></li>
		<li role="presentation"><a href="<?php echo $this->url('admin/acledit', array('action'=>'roles'));?>"><?php echo $this->translate("Rollen bearteiten")?></a></li>
		<li role="presentation"><a href="<?php echo $this->url('admin/acledit', array('action'=>'addresource'));?>"><?php echo $this->translate("Resource hinzufügen")?></a></li>
		<li role="presentation"><a href="<?php echo $this->url('admin/acledit', array('action'=>'resources'));?>"><?php echo $this->translate("Resourcen bearteiten")?></a></li>
	</ul>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Berechtigungen verwalten"); ?></span>
		</label>
	</div>
	<div class="panel-body">
	
		<?php include 'index.matrix.phtml'; ?>
		
		<?php echo $this->output ?>
	</div>
</div>
