<div class="table-responsive">
    <table class="table table-striped table-hover datatable crud" data-src="<?php echo $this->url('admin/acledit', array('action'=>'resources')) ?>" data-myapp-datatable>
        <thead>
            <tr>
                <th data-column="resourceslug"><?php echo $this->translate("resource slug")?></th>
                <th data-column="resourcename"><?php echo $this->translate("resource name")?></th>
                <th class="actions">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($resources as $resource) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($resource->resourceslug);?></td>
                <td><?php echo $this->escapeHtml($resource->resourcename);?></td>
                <td>
                    <div class="button-group tiny btn-group btn-group-xs">
                        <a class="button btn btn-default tiny btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/acledit',
                            array('action'=>'editresource', 'acl_id' => $resource->aclresources_id));?>"><span class="fa fa-pencil"></span> <?php echo $this->translate("edit"); ?></a>
                        <a class="button btn btn-default tiny btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/acledit',
                            array('action'=>'deleteresource', 'acl_id' => $resource->aclresources_id));?>"><span class="fa fa-trash-o"></span> <?php echo $this->translate("delete"); ?></a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php echo $this->output ?>
