<div class="table-responsive">
	<table class="table table-striped table-hover datatable crud" data-src="<?php echo $this->url('admin/acledit', array('action'=>'roles')) ?>" data-myapp-datatable>
		<thead>
			<tr>
				<th data-column="roleslug"><?php echo $this->translate("role slug")?></th>
				<th data-column="rolename"><?php echo $this->translate("role name")?></th>
				<th class="actions">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($roles as $role) : ?>
			<tr>
				<td><?php echo $this->escapeHtml($role->roleslug);?></td>
				<td><?php echo $this->escapeHtml($role->rolename);?></td>
				<td>
					<div class="button-group tiny btn-group btn-group-xs">
						<a class="button btn btn-default tiny btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/acledit',
							array('action'=>'editrole', 'acl_id' => $role->aclroles_id));?>"><span class="fa fa-pencil"></span> <?php echo $this->translate("edit"); ?></a>
						<a class="button btn btn-default tiny btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/acledit',
							array('action'=>'deleterole', 'acl_id' => $role->aclroles_id));?>"><span class="fa fa-trash-o"></span> <?php echo $this->translate("delete"); ?></a>
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<?php echo $this->output ?>
