<div class="well well-sm">
	<ul class="nav nav-pills">
    	<li role="presentation"><a href="<?php echo $this->url('admin/acledit', array('action'=>'addrole'));?>"><?php echo $this->translate("Neue Rolle hinzufügen")?></a></li>
	</ul>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Rollen verwalten"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<tr>
				    <th><?php echo $this->translate("Rollen-Slug")?></th>
				    <th><?php echo $this->translate("Rollen-Name")?></th>
				    <th>&nbsp;</th>
				</tr>
				<?php foreach ($roles as $role) : ?>
				<tr>
				    <td><?php echo $this->escapeHtml($role->roleslug);?></td>
				    <td><?php echo $this->escapeHtml($role->rolename);?></td>
				    <td>
				        <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/acledit',
				            array('action'=>'editrole', 'acl_id' => $role->aclroles_id));?>"><?php echo $this->translate("ändern"); ?></a>
				        <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/acledit',
				            array('action'=>'deleterole', 'acl_id' => $role->aclroles_id));?>"><?php echo $this->translate("entfernen"); ?></a>
				    </td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
		<?php echo $this->output ?>
	</div>
</div>
