<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("manage roles"); ?></span>
		</label>
	</div>
	<div class="panel-body panel-toolbar">
		<div class="btn-group btn-group-sm">
			<a class="btn btn-default btn-clean btn-cta-xhr btn-sm" href="<?php echo $this->url('admin/acledit', array('action'=>'addrole'));?>"><span class="fa fa-plus"></span> <?php echo $this->translate("add role")?></a>
		</div>
		<div class="btn-group btn-group-sm">
			<a class="btn btn-default btn-clean btn-cta-xhr btn-sm" href="<?php echo $this->url('admin/acledit');?>"><span class="fa fa-plus"></span> <?php echo $this->translate("ACL")?></a>
			<a class="btn btn-default btn-clean btn-cta-xhr btn-sm" href="<?php echo $this->url('admin/acledit', array('action'=>'resources'));?>"><span class="fa fa-plus"></span> <?php echo $this->translate("manage resources")?></a>
		</div>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-hover datatable">
				<thead>
					<tr>
					    <th><?php echo $this->translate("role slug")?></th>
					    <th><?php echo $this->translate("role name")?></th>
					    <th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($roles as $role) : ?>
					<tr>
					    <td><?php echo $this->escapeHtml($role->roleslug);?></td>
					    <td><?php echo $this->escapeHtml($role->rolename);?></td>
					    <td>
						    <div class="btn-group btn-group-xs">
						        <a class="btn btn-default btn-xs btn-clean btn-cta-xhr" href="<?php echo $this->url('admin/acledit',
						            array('action'=>'editrole', 'acl_id' => $role->aclroles_id));?>"><span class="fa fa-pencil"></span> <?php echo $this->translate("edit"); ?></a>
						        <a class="btn btn-default btn-xs btn-clean btn-cta-xhr" href="<?php echo $this->url('admin/acledit',
						            array('action'=>'deleterole', 'acl_id' => $role->aclroles_id));?>"><span class="fa fa-trash-o"></span> <?php echo $this->translate("delete"); ?></a>
						    </div>
					    </td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<?php echo $this->output ?>
	</div>
</div>
