<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Neue Einstellung hinzufügen"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php 
			$form->setAttribute('action', $this->url('admin/settingsedit', array('action' => 'add')));
			$form->prepare();
			
			echo $this->form()->openTag($form); ?>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('type')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('type')); ?>
				<?php echo $this->formInput($form->get('type')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('type')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('name')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('name')); ?>
				<?php echo $this->formInput($form->get('name')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('name')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('value')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('value')); ?>
				<?php echo $this->formInput($form->get('value')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('value')); ?>
			</div>
			<hr />
			<?php echo $this->formHidden($form->get('settings_id')); ?>
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<a class="btn btn-danger" href="<?php echo $this->url('admin/settingsedit'); ?>"><?php echo $this->translate("abbrechen"); ?></a>
		<?php echo $this->form()->closeTag($form); ?>
	</div>
</div>
