<?php 
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {
	$form = $this->form;
	$form->setAttribute('action', $this->url('admin/settingsedit', array('action' => 'add')));
	$form->setAttribute('class', 'form-xhr');
	$form->prepare();
		
	$formHTML = $this->form()->openTag($form);
	$formHTML .= $oComponents->formGroup($form, "scope");
	$formHTML .= $oComponents->formGroup($form, "ref_id");
	$formHTML .= $oComponents->formGroup($form, "type");
	$formHTML .= $oComponents->formGroup($form, "name");
	$formHTML .= $oComponents->formGroup($form, "value");
	$formHTML .= '<hr />'; 
	$formHTML .= $this->formHidden($form->get('settings_id'));
	$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary')));
	$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default')));
	$formHTML .= '<a class="btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'. $this->url('admin/settingsedit') .'">'. $this->translate("cancel") .'</a>';
	$formHTML .=  $this->form()->closeTag($form);
		
	echo $formHTML;
}
/* ?>
<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("add setting"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php 
			$form->setAttribute('action', $this->url('admin/settingsedit', array('action' => 'add')));
			$form->prepare();
			
			echo $this->form()->openTag($form); ?>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('scope')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('scope')); ?>
				<?php echo $this->formInput($form->get('scope')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('scope')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('ref_id')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('ref_id')); ?>
				<?php echo $this->formInput($form->get('ref_id')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('ref_id')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('type')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('type')); ?>
				<?php echo $this->formInput($form->get('type')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('type')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('name')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('name')); ?>
				<?php echo $this->formInput($form->get('name')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('name')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('value')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('value')); ?>
				<?php echo $this->formInput($form->get('value')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('value')); ?>
			</div>
			<hr />
			<?php echo $this->formHidden($form->get('settings_id')); ?>
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary'))); ?>
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<a class="btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="<?php echo $this->url('admin/settingsedit'); ?>"><?php echo $this->translate("cancel"); ?></a>
		<?php echo $this->form()->closeTag($form); ?>
	</div>
</div>
*/