<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("edit setting"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url(
			    'admin/settingsedit',
			    array(
			        'action'		=> 'edit',
			        'set_id'		=> $this->settings_id,
			    )
			));
			$form->prepare();
		
			echo $this->form()->openTag($form); ?>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('scope')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('scope')); ?>
				<?php echo $this->formInput($form->get('scope')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('scope')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('ref_id')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('ref_id')); ?>
				<?php echo $this->formInput($form->get('ref_id')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('ref_id')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('type')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('type')); ?>
				<?php echo $this->formInput($form->get('type')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('type')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('name')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('name')); ?>
				<?php echo $this->formInput($form->get('name')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('name')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('value')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('value')); ?>
				<?php echo $this->formInput($form->get('value')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('value')); ?>
			</div>
			<hr />
			<?php echo $this->formHidden($form->get('settings_id')); ?>
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary'))); ?>
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<a class="btn btn-danger btn-cta-xhr-close" href="<?php echo $this->url('admin/settingsedit'); ?>"><?php echo $this->translate("cancel"); ?></a>
		<?php echo $this->form()->closeTag($form); ?>
	</div>
</div>
