<div class="well well-sm">
	<ul class="nav nav-pills">
    	<li role="presentation"><a href="<?php echo $this->url('admin/settingsedit', array('action'=>'add'));?>"><?php echo $this->translate("add setting")?></a></li>
	</ul>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("manage settings"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<tr>
				    <th><?php echo $this->translate("type")?></th>
				    <th><?php echo $this->translate("name")?></th>
				    <th><?php echo $this->translate("value")?></th>
				    <th>&nbsp;</th>
				</tr>
				<?php foreach ($settingsdata as $settings) : ?>
				<tr>
				    <td><?php echo $this->escapeHtml($settings->type);?></td>
				    <td><?php echo $this->escapeHtml($settings->name);?></td>
				    <td><?php echo $this->escapeHtml($settings->value);?></td>
				    <td>
				        <a class="btn btn-default btn-xs btn-clean btn-cta-xhr" href="<?php echo $this->url('admin/settingsedit',
				            array('action'=>'edit', 'set_id' => $settings->settings_id));?>"><?php echo $this->translate("edit"); ?></a>
				        <a class="btn btn-default btn-xs btn-clean btn-cta-xhr" href="<?php echo $this->url('admin/settingsedit',
				            array('action'=>'delete', 'set_id' => $settings->settings_id));?>"><?php echo $this->translate("delete"); ?></a>
				    </td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
		<?php echo $this->output ?>
	</div>
</div>
