<div class="table-responsive">
	<table id="settingstable" class="table table-striped table-hover datatable crud" data-src="<?php echo $this->url('admin/settingsedit') ?>">
		<thead>
			<tr>
				<th data-column="scope"><?php echo $this->translate("scope")?></th>
				<th data-column="ref_id"><?php echo $this->translate("reference")?></th>
				<th data-column="type"><?php echo $this->translate("type")?></th>
				<th data-column="name"><?php echo $this->translate("name")?></th>
				<th data-column="value"><?php echo $this->translate("value")?></th>
				<th class="actions">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($settingsdata as $settings) : ?>
			<tr>
				<td><?php echo $this->escapeHtml($settings->scope); ?></td>
				<td><?php echo $this->escapeHtml($settings->ref_id); ?></td>
				<td><?php echo $this->escapeHtml($settings->type); ?></td>
				<td><?php echo $this->escapeHtml($settings->name); ?></td>
				<td><?php echo $this->escapeHtml($settings->value); ?></td>
				<td>
					<div class="button-group tiny btn-group btn-group-xs">
						<a class="button btn btn-default tiny btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/settingsedit',
							array('action'=>'edit', 'set_id' => $settings->settings_id));?>"><span class="fa fa-pencil"></span> <?php echo $this->translate("edit"); ?></a>
						<a class="button btn btn-default tiny btn-xs btn-clean btn-cta-xhr cta-xhr-modal" href="<?php echo $this->url('admin/settingsedit',
							array('action'=>'delete', 'set_id' => $settings->settings_id));?>"><span class="fa fa-trash-o"></span> <?php echo $this->translate("delete"); ?></a>
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<?php echo $this->output ?>
