<section>
	<h3><?php echo sprintf($this->translate('change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
	<?php if ($status === true) : ?>
	<div class="alert alert-success"><?php echo $this->translate('password changed successfully');?></div>
	<?php elseif ($status === false) : ?>
	<div class="alert alert-error"><?php echo $this->translate('unable to update your password, please try again'); ?></div>
	<?php endif; ?>
	<?php
		$form = $this->changePasswordForm;
		
		$form->prepare();
		$form->setAttribute('action', $this->url('zfcuser/changepassword'));
		$form->setAttribute('method', 'post');
		
		$emailElement = $form->get('identity');
		$emailElement->setValue($this->zfcUserIdentity()->getEmail());
		
		echo $this->form()->openTag($form); ?>
		<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('identity')))) ? ' has-error' : '' ?>">
			<?php echo $this->formHidden($form->get('identity')->setAttributes(array('class' => 'form-control'))); ?>
		</div>
		<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('credential')))) ? ' has-error' : '' ?>">
			<?php echo $this->formLabel($form->get('credential')->setAttributes(array('class' => 'control-label'))); ?>
			<?php echo $this->formInput($form->get('credential')->setAttributes(array('class' => 'form-control'))); ?>
			<?php echo $this->formElementErrors($form->get('credential')); ?>
		</div>
		<hr />
		<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newCredential')))) ? ' has-error' : '' ?>">
			<?php echo $this->formLabel($form->get('newCredential')->setAttributes(array('class' => 'control-label'))); ?>
			<?php echo $this->formInput($form->get('newCredential')->setAttributes(array('class' => 'form-control'))); ?>
			<?php echo $this->formElementErrors($form->get('newCredential')); ?>
		</div>
		<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newCredentialVerify')))) ? ' has-error' : '' ?>">
			<?php echo $this->formLabel($form->get('newCredentialVerify')->setAttributes(array('class' => 'control-label'))); ?>
			<?php echo $this->formInput($form->get('newCredentialVerify')->setAttributes(array('class' => 'form-control'))); ?>
			<?php echo $this->formElementErrors($form->get('newCredentialVerify')); ?>
		</div>
		<hr />
		<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' => 'button primary btn btn-primary'))); ?>
		<input class="button btn btn-default" type="reset" value="<?php echo $this->translate("reset"); ?>" />
		<a class="button alert btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="<?php echo $this->url('zfcuser'); ?>"><?php echo $this->translate("cancel"); ?></a>
	<?php echo $this->form()->closeTag(); ?>
</section>
