<?php if (!$showForm) {
	echo $content;
} else { 
	$form = $this->userprofileForm;
	$form->prepare();
	$form->setAttribute('action', $this->url('zfcuser/edituserprofile'));
	$form->setAttribute('method', 'post');
	$form->setAttribute('class', 'form-xhr');
	
	echo $this->form()->openTag($form); ?>
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('street')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('street')); ?>
		<?php echo $this->formInput($form->get('street')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('street')); ?>
	</div>
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('city')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('city')); ?>
		<?php echo $this->formInput($form->get('city')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('city')); ?>
	</div>
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('phone')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('phone')); ?>
		<?php echo $this->formInput($form->get('phone')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('phone')); ?>
	</div>
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('cell')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('cell')); ?>
		<?php echo $this->formInput($form->get('cell')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('cell')); ?>
	</div>
	<hr />
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('facebook')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('facebook')); ?>
		<?php echo $this->formInput($form->get('facebook')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('facebook')); ?>
	</div>
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('twitter')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('twitter')); ?>
		<?php echo $this->formInput($form->get('twitter')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('twitter')); ?>
	</div>
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('skype')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('skype')); ?>
		<?php echo $this->formInput($form->get('skype')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('skype')); ?>
	</div>
	<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('icq')))) ? ' has-error' : '' ?>">
		<?php echo $this->formLabel($form->get('icq')); ?>
		<?php echo $this->formInput($form->get('icq')->setAttributes(array('class' => 'form-control'))); ?>
		<?php echo $this->formElementErrors($form->get('icq')); ?>
	</div>
	<hr />
	<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary'))); ?>
	<input class="btn btn-default" type="reset" value="<?php echo $this->translate("reset"); ?>" />
	<a class="btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="<?php echo $this->url('zfcuser'); ?>"><?php echo $this->translate("cancel"); ?></a>
    <?php if ($this->redirect): ?><input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" /><?php endif ?>
    <input type="hidden" name="user_id" value="<?php echo $this->escapeHtml($this->userId) ?>" />
<?php echo $this->form()->closeTag();
} ?>