<?php
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $oBootstrap **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $oComponents **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $oUser **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {
		/** @var \Admin\Form\UserDataForm $form **/
		$form = $this->userdataForm;
		$form->setAttribute('action', $this->url('zfcuser/edituserdata'));
		$form->setAttribute('method', 'post');
		$form->setAttribute('class', 'form-xhr');
		$form->prepare();
		
		$formHTML = $this->form()->openTag($form);
		$formHTML .= $oComponents->formGroup($form, "display_name");
		
		$formHTML .= '<hr />';
		$formHTML .= '<div class="form-group">';
		$formHTML .= $this->formHidden($form->get('user_id'));
		$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'button primary btn btn-primary'))->setOption('type', 'button'));
		$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'button btn btn-default'))->setOption('type', 'button'));
		$formHTML .= '<a class="button alert btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'. $this->url('zfcuser') .'">'. $this->translate("cancel") .'</a>';
		$formHTML .= '</div class="form-group">';
		$formHTML .=  $this->form()->closeTag($form);
			
		echo $formHTML;	
}