<?php
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

if ($showForm) {
		/** @var \Zend\Form\Form $form **/
		$form = $this->userdataForm;
		$form->setAttribute('action', $this->url('zfcuser/edituserdata'));
		$form->setAttribute('method', 'post');
		$form->setAttribute('class', 'form-xhr');
		$form->prepare();
		print_r($form->getMessages());
		$formHTML = $this->form()->openTag($form);
		$formHTML .= $oComponents->formGroup($form, "display_name");
		
		$formHTML .= '<hr />';
		$formHTML .= '<div class="form-group">';
		$formHTML .= $this->formHidden($form->get('user_id'));
		$formHTML .= $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary'))->setOption('type', 'button'));
		$formHTML .= $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))->setOption('type', 'button'));
		$formHTML .= '<a class="btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="'. $this->url('admin/default', array("controller" => "users")) .'">'. $this->translate("cancel") .'</a>';
		$formHTML .= '</div class="form-group">';
		$formHTML .=  $this->form()->closeTag($form);
			
		echo $formHTML;
		
		/* echo $this->form()->openTag($form); ?>
		<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('display_name')))) ? ' has-error' : '' ?>">
			<?php echo $this->formLabel($form->get('display_name')); ?>
			<?php echo $this->formInput($form->get('display_name')->setAttributes(array('class' => 'form-control'))); ?>
			<?php echo $this->formElementErrors($form->get('display_name')); ?>
		</div>
		<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-primary'))->setOption('type', 'button')); ?>
		<?php echo $this->formSubmit($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))->setOption('type', 'button')); ?>
		<a class="btn btn-danger btn-cta-xhr cta-xhr-modal-close" href="<?php echo $this->url('zfcuser'); ?>"><?php echo $this->translate("cancel"); ?></a>
		<?php if ($this->redirect): ?><input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" /><?php endif ?>
		<input type="hidden" name="user_id" value="<?php echo $this->escapeHtml($this->userId) ?>" />
	<?php echo $this->form()->closeTag(); */
		
}