<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><strong><?php echo $this->translate('user profile'); ?></strong></span>
	</div>
	<div class="panel-body panel-toolbar">
		<div class="btn-group btn-group-sm" role="group" aria-label="<?php echo $this->translate('user profile actions'); ?>">
			<a class="btn btn-default btn-clean btn-sm" href="<?php echo $this->url('admin/default', array("controller" => "user", "action" => "edituserprofile")) ?>"><span class="fa fa-edit"></span> <?php echo $this->translate('edit profile'); ?></a>
			<a class="btn btn-default btn-clean btn-sm" href="<?php echo $this->url('zfcuser/changeemail') ?>"><span class="fa fa-envelope"></span> <?php echo $this->translate('change email'); ?></a>
			<a class="btn btn-default btn-clean btn-sm" href="<?php echo $this->url('zfcuser/changepassword') ?>"><span class="fa fa-lock"></span> <?php echo $this->translate('change password'); ?></a>
			<a class="btn btn-default btn-clean btn-sm" href="<?php echo $this->url('zfcuser/logout') ?>"><span class="fa fa-power-off"></span> <?php echo $this->translate('logout'); ?></a>
		</div>
	</div>
	<div class="panel-body">
		<section class="row">
			<div class="col-md-2">
				<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
			</div>
			<div class="col-md-10">
				<h3><?php echo $this->translate('Hallo'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
				<hr />
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('user')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getUsername()); ?>, 
						<a href="mailto:<?php echo ($this->zfcUserIdentity()->getEmail()); ?>" target="_blank"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getEmail()); ?></a></span>
				</div>
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('role')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getAclrole()); ?></span>
				</div>
				<hr />
			</div>
		</section>
	</div>
	<div class="panel-body">
		
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="h1">
			<h4 class="panel-title">
				<a role="button" data-toggle="collapse" data-parent="#accordion" href="#p1" aria-expanded="true" aria-controls="p1">
					<?php echo $this->escapeHtml($this->translate('address')); ?>
				</a>
			</h4>
		</div>
		<div id="p1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="h1">
			<div class="panel-body">
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('street')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getStreet()); ?></span>
				</div>
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('city')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getCity()); ?></span>
				</div>
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('phone')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getPhone()); ?></span>
				</div>
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('mobile')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getPhone()); ?></span>
				</div>
			</div>
		</div>
	</div>
      
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="h2">
			<h4 class="panel-title">
				<a role="button" data-toggle="collapse" data-parent="#accordion" href="#p2" aria-expanded="true" aria-controls="p2">
					<?php echo $this->escapeHtml($this->translate('messengers')); ?>
				</a>
			</h4>
		</div>
		<div id="p2" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="h2">
			<div class="panel-body">
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('twitter')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getStreet()); ?></span>
				</div>
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('facebook')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getCity()); ?></span>
				</div>
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('skype')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getPhone()); ?></span>
				</div>
				<div class="row">
					<span class="col-md-2"><?php echo $this->escapeHtml($this->translate('icq')); ?>:</span>
					<span class="col-md-10"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getPhone()); ?></span>
				</div>
			</div>
		</div>
	</div>
      
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="h3">
			<h4 class="panel-title">
				<a role="button" data-toggle="collapse" data-parent="#accordion" href="#p3" aria-expanded="true" aria-controls="p3">
					<?php echo $this->escapeHtml($this->translate('others...')); ?>
				</a>
			</h4>
		</div>
		<div id="p3" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="h3">
			<div class="panel-body">
				...
			</div>
		</div>
	</div>
      
</div>


	</div>
</div>

