<?php if (!$this->enableRegistration) { ?>
<div class="panel panel-warning">
    <div class="panel-heading">
        <span class="panel-title"><strong><?php echo $this->translate('register user'); ?></strong></span>
    </div>
    <div class="panel-body">
        <p class="text-xl"><?php echo $this->translate('registration is currently not available, please try again later'); ?></p>
    </div>
</div>
<?php } else { ?>
<section>
    <?php
        $form = $this->registerForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/register'));
        $form->setAttribute('method', 'post');
        
        echo $this->form()->openTag($form); ?>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('username')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('username')); ?>
            <?php echo $this->formInput($form->get('username')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('username')); ?>
        </div>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('email')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('display_name')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('display_name')); ?>
            <?php echo $this->formInput($form->get('display_name')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('display_name')); ?>
        </div>
        <hr />
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('password')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('password')); ?>
            <?php echo $this->formInput($form->get('password')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('passwordVerify')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('passwordVerify')); ?>
            <?php echo $this->formInput($form->get('passwordVerify')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('passwordVerify')); ?>
        </div>
        <hr />
        <?php 
        try {
        	$captcha = $form->get('captcha');
        } catch (\Exception $ex ) {
        	$captcha = false;
        }
        if ($captcha) { 
        ?>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('captcha')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('captcha')); ?>
            <?php echo $this->formCaptcha($form->get('captcha')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('captcha')); ?>
        </div>
        <?php } ?>
        <hr />
        <?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'button primary btn btn-primary', 'value' => $this->translate('register')))); ?>
        <input class="button secondary btn btn-default" type="reset" value="<?php echo $this->translate("reset"); ?>" />
        <a class="button alert btn btn-danger" href="<?php echo $this->url('home'); ?>"><?php echo $this->translate("cancel"); ?></a>
        <?php if ($this->redirect): ?><input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" /><?php endif ?>
    <?php echo $this->form()->closeTag(); ?>
</section>
<?php } ?>