<?php if (!$this->enableRegistration) { ?>
<div class="panel panel-warning">
	<div class="panel-heading">
		<span class="panel-title"><strong><?php echo $this->translate('Registrierung'); ?></strong></span>
	</div>
	<div class="panel-body">
		<p class="text-xl"><?php echo $this->translate('Registrierungen sind derzeit nicht möglich.'); ?></p>
	</div>
</div>
<?php } else { ?>
<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><strong><?php echo $this->translate('Registrierung'); ?></strong></span>
	</div>
	<div class="panel-body">
		<?php
			$form = $this->registerForm;
			$form->prepare();
			$form->setAttribute('action', $this->url('zfcuser/register'));
			$form->setAttribute('method', 'post');
			
			echo $this->form()->openTag($form) ?>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('username')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('username')); ?>
				<?php echo $this->formInput($form->get('username')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('username')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('email')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('email')); ?>
				<?php echo $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('email')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('display_name')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('display_name')); ?>
				<?php echo $this->formInput($form->get('display_name')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('display_name')); ?>
			</div>
			<hr />
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('password')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('password')); ?>
				<?php echo $this->formInput($form->get('password')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('password')); ?>
			</div>
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('passwordVerify')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('passwordVerify')); ?>
				<?php echo $this->formInput($form->get('passwordVerify')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('passwordVerify')); ?>
			</div>
			<hr />
			<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('captcha')))) ? ' has-error' : '' ?>">
				<?php echo $this->formLabel($form->get('captcha')); ?>
				<?php echo $this->formCaptcha($form->get('captcha')->setAttributes(array('class' => 'form-control'))); ?>
				<?php echo $this->formElementErrors($form->get('captcha')); ?>
			</div>
			<hr />
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-default', 'value' => $this->translate('Registrieren')))); ?>
			<a class="btn btn-danger" href="<?php echo $this->url('home'); ?>"><?php echo $this->translate("abbrechen"); ?></a>
	        <?php if ($this->redirect): ?><input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" /><?php endif ?>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>
<?php } ?>