<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><strong><?php echo $this->translate('set password'); ?></strong></span>
	</div>
	<div class="panel-body">
		<section>
			<?php if ($status === true) : ?>
			<div class="alert alert-success"><?php echo $this->translate('password set successfully'); ?></div>
			<?php elseif ($status === false) : ?>
			<div class="alert alert-error"><?php echo $this->translate('unable to set your password, please try again'); ?></div>
			<?php endif; ?>
			<?php
			
			$form = $this->requestPasswordResetForm;
			
			$form->prepare();
			$form->setAttribute('action', $this->url('userrequestpasswordreset'));
			$form->setAttribute('method', 'post');
			
			?>
			<?php echo $this->form()->openTag($form) ?>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('identity')))) ? ' has-error' : '' ?>">
					<?php echo $this->formLabel($form->get('identity')->setAttributes(array('class' => 'control-label'))); ?>
					<?php echo $this->formInput($form->get('identity')->setAttributes(array('class' => 'form-control'))); ?>
					<?php echo $this->formElementErrors($form->get('identity')); ?>
				</div>
				<hr />
			    <?php if ($this->redirect): ?>
			    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
			    <?php endif ?>
			    <input type="hidden" name="ide" value="<?php echo $this->redirect ?>" />
				<?php echo $this->formHidden($form->get('identity')); ?>
				<input class="btn btn-default" type="submit" name="submit" value="<?php echo $this->translate("save"); ?>" />
				<a class="btn btn-default" href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate("cancel"); ?></a>
			<?php echo $this->form()->closeTag() ?>
		</section>
	</div>
</div>
