<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><strong><?php echo $this->translate('change email'); ?></strong></span>
	</div>
	<div class="panel-body">
		<section>
			<h3><?php echo sprintf($this->translate('change email for %s'), $this->zfcUserDisplayName()); ?></h3>
			<?php if ($status === true) : ?>
			<div class="alert alert-success"><?php echo $this->translate('email address changed successfully'); ?></div>
			<?php elseif ($status === false) : ?>
			<div class="alert alert-error"><?php echo $this->translate('unable to update your email address, please try again'); ?></div>
			<?php endif; ?>
			<?php
			
			$form = $this->changeEmailForm;
			
			$form->prepare();
			$form->setAttribute('action', $this->url('userrequestpasswordreset'));
			$form->setAttribute('method', 'post');
			
			?>
			<?php echo $this->form()->openTag($form) ?>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newIdentity')))) ? ' has-error' : '' ?>">
					<?php echo $this->formLabel($form->get('newIdentity')->setAttributes(array('class' => 'control-label'))); ?>
					<?php echo $this->formInput($form->get('newIdentity')->setAttributes(array('class' => 'form-control'))); ?>
					<?php echo $this->formElementErrors($form->get('newIdentity')); ?>
				</div>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newIdentityVerify')))) ? ' has-error' : '' ?>">
					<?php echo $this->formLabel($form->get('newIdentityVerify')->setAttributes(array('class' => 'control-label'))); ?>
					<?php echo $this->formInput($form->get('newIdentityVerify')->setAttributes(array('class' => 'form-control'))); ?>
					<?php echo $this->formElementErrors($form->get('newIdentityVerify')); ?>
				</div>
				<hr />
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('credential')))) ? ' has-error' : '' ?>">
					<?php echo $this->formLabel($form->get('credential')->setAttributes(array('class' => 'control-label'))); ?>
					<?php echo $this->formInput($form->get('credential')->setAttributes(array('class' => 'form-control'))); ?>
					<?php echo $this->formElementErrors($form->get('credential')); ?>
				</div>
				<hr />
			    <?php if ($this->redirect): ?>
			    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
			    <?php endif ?>
				<?php echo $this->formHidden($form->get('identity')); ?>
				<input class="btn btn-default" type="submit" name="submit" value="<?php echo $this->translate("save"); ?>" />
				<a class="btn btn-default" href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate("cancel"); ?></a>
			<?php echo $this->form()->closeTag() ?>
		</section>
	</div>
</div>
