<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><strong><?php echo $this->translate('reset password'); ?></strong></span>
	</div>
	<div class="panel-body">
		<section>
			<p><?php echo $this->translate('To set a new password enter your username or email used for registration. You will recieve a mail with a link to set your new password.'); ?></p>
			<?php
			
			$form = $this->requestPasswordResetForm;
			
			$form->prepare();
			$form->setAttribute('action', $this->url('userrequestpasswordreset'));
			$form->setAttribute('method', 'post');
			
			?>
			<?php echo $this->form()->openTag($form) ?>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('identity')))) ? ' has-error' : '' ?>">
					<?php echo $this->formLabel($form->get('identity')->setAttributes(array('class' => 'control-label'))); ?>
					<?php echo $this->formInput($form->get('identity')->setAttributes(array('class' => 'form-control'))); ?>
					<?php echo $this->formElementErrors($form->get('identity')); ?>
				</div>
				<hr />
			    <?php if ($this->redirect): ?>
			    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
			    <?php endif ?>
				<?php echo $this->formInput($form->get('submit')->setAttributes(array('class' => 'btn btn-primary', 'value' => $this->translate("request password reset")))); ?>
				<a class="btn btn-danger" href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate("cancel"); ?></a>
			<?php echo $this->form()->closeTag() ?>
		</section>
	</div>
</div>
