<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title"><strong><?php echo $this->translate('set password'); ?></strong></span>
	</div>
	<div class="panel-body">
		<section>
			<h3><?php echo sprintf($this->translate('set password for %s'), $this->zfcUserDisplayName()); ?></h3>
			<?php if ($status === true) : ?>
			<div class="alert alert-success"><?php echo $this->translate('password set successfully');?></div>
			<?php elseif ($status === false) : ?>
			<div class="alert alert-error"><?php echo $this->translate('unable to set your password, please try again'); ?></div>
			<?php endif; ?>
			<?php
				$form = $this->changePasswordForm;
				
				$form->prepare();
				$form->setAttribute('action', $this->url('userresetpassword'));
				$form->setAttribute('method', 'post');
				
				$emailElement = $form->get('identity');
				$emailElement->setValue($this->zfcUserIdentity()->getEmail());
				
				$emailElement = $form->get('token');
				$emailElement->setValue($this->resetToken);
				
				echo $this->form()->openTag($form); ?>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newCredential')))) ? ' has-error' : '' ?>">
					<?php echo $this->formLabel($form->get('newCredential')->setAttributes(array('class' => 'control-label'))); ?>
					<?php echo $this->formInput($form->get('newCredential')->setAttributes(array('class' => 'form-control'))); ?>
					<?php echo $this->formElementErrors($form->get('newCredential')); ?>
				</div>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newCredentialVerify')))) ? ' has-error' : '' ?>">
					<?php echo $this->formLabel($form->get('newCredentialVerify')->setAttributes(array('class' => 'control-label'))); ?>
					<?php echo $this->formInput($form->get('newCredentialVerify')->setAttributes(array('class' => 'form-control'))); ?>
					<?php echo $this->formElementErrors($form->get('newCredentialVerify')); ?>
				</div>
				<hr />
				<?php
					//echo $this->formInput($form->get('identity'));
					echo $this->formInput($form->get('submit')->setAttributes(array('class' => 'btn btn-default')));
				?>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('identity')))) ? ' has-error' : '' ?>">
					<?php echo $this->formHidden($form->get('identity')->setAttributes(array('class' => 'form-control'))); ?>
				</div>
				<div class="form-group<?php echo (!empty($this->formElementErrors($form->get('token')))) ? ' has-error' : '' ?>">
					<?php echo $this->formHidden($form->get('token')->setAttributes(array('class' => 'form-control'))); ?>
				</div>
			<?php echo $this->form()->closeTag(); ?>
		</section>
	</div>
</div>
