<section>
    <p><?php echo $this->translate('Enter your new password and verify.'); ?></p>
    <?php
        $form = $this->resetPasswordForm;
        
        $form->prepare();
        $form->setAttribute('action', $this->url('userresetpassword'));
        $form->setAttribute('method', 'post');
        
        $emailElement = $form->get('identity');
        $emailElement->setValue($this->user->getEmail());
        
        $emailElement = $form->get('token');
        $emailElement->setValue($this->resetToken);
        
        echo $this->form()->openTag($form); ?>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newCredential')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('newCredential')->setAttributes(array('class' => 'control-label'))); ?>
            <?php echo $this->formInput($form->get('newCredential')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('newCredential')); ?>
        </div>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('newCredentialVerify')))) ? ' has-error' : '' ?>">
            <?php echo $this->formLabel($form->get('newCredentialVerify')->setAttributes(array('class' => 'control-label'))); ?>
            <?php echo $this->formInput($form->get('newCredentialVerify')->setAttributes(array('class' => 'form-control'))); ?>
            <?php echo $this->formElementErrors($form->get('newCredentialVerify')); ?>
        </div>
        <hr />
        <?php echo $this->formInput($form->get('submit')->setAttributes(array('class' => 'button primary btn btn-primary'))); ?>
        <a class="button alert btn btn-danger" href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate("cancel"); ?></a>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('identity')))) ? ' has-error' : '' ?>">
            <?php echo $this->formHidden($form->get('identity')->setAttributes(array('class' => 'form-control'))); ?>
        </div>
        <div class="form-group<?php echo (!empty($this->formElementErrors($form->get('token')))) ? ' has-error' : '' ?>">
            <?php echo $this->formHidden($form->get('token')->setAttributes(array('class' => 'form-control'))); ?>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</section>